# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website', '0003_auto_20160522_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added to list'),
        ),
    ]
