# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-20 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website', '0004_auto_20160522_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=1)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added to list')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='grocery_visit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal_website.GroceryVisit'),
        ),
    ]
