# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website', '0005_auto_20160820_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='whether this item is in the active grocery list'),
        ),
    ]
